# action.yml
name: "cache-self-hosted-action"
author: "Yogendra Singh"
description: "A Github Action allows caching dependencies and build outputs to improve workflow execution time."
branding:
  icon: 'archive'
  color: 'gray-dark'
inputs:
  path:
    description: "Path of file or directory to cache and restore."
    required: true
  key:
    description: "An explicit key for restoring and saving the cache."
    required: false
    default: "cache"
  prefix:
    description: "Cache storage hash key."
    required: false
    default: "cache"
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/post/index.js"
